//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketplaceWebPortal.EntityLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public Nullable<int> ModelID { get; set; }
        public Nullable<int> ManufacturerID { get; set; }
        public string ProductImgUrl { get; set; }
        public Nullable<int> SubCategoryID { get; set; }
        public string ProductName { get; set; }
    }
}
