//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketplaceWebPortal.EntityLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeriesModel
    {
        public int s_m_id { get; set; }
        public int SeriesID { get; set; }
        public Nullable<int> ModelID { get; set; }
    
        public virtual Model Model { get; set; }
        public virtual Series Series { get; set; }
    }
}
