//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketplaceWebPortal.EntityLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCategory1
    {
        public int SubCategoryID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string SubCategoryName { get; set; }
    
        public virtual Category1 Category { get; set; }
    }
}
