//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketplaceWebPortal.EntityLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechSpecFilter
    {
        public int TechSpecID { get; set; }
        public Nullable<int> PropertyID { get; set; }
        public Nullable<int> SubCategoryID { get; set; }
        public Nullable<int> MaxVal { get; set; }
        public Nullable<int> MinVal { get; set; }
    
        public virtual Property Property { get; set; }
        public virtual SubCategory SubCategory { get; set; }
    }
}
